package cn.yajienet.huanaer.ui.theme

import androidx.compose.ui.graphics.Color

// ============================================================
// Default Theme Colors (蓝紫色品牌系) — 保留作为 fallback
// ============================================================

// Light Theme Colors
val LightPrimary = Color(0xFF5A67D8)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE8EBFA)
val LightOnPrimaryContainer = Color(0xFF1A1E4C)
val LightSecondary = Color(0xFF667EEA)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE3E7FC)
val LightOnSecondaryContainer = Color(0xFF1E254E)
val LightTertiary = Color(0xFF4C51BF)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDDE2F7)
val LightOnTertiaryContainer = Color(0xFF16123B)
val LightError = Color(0xFFD32F2F)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFEBEE)
val LightOnErrorContainer = Color(0xFF5C1313)
val LightBackground = Color(0xFFF5F7FA)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceContainer = Color(0xFFF0F2F5)
val LightSurfaceContainerHigh = Color(0xFFE8EAED)
val LightSurfaceContainerHighest = Color(0xFFE0E3E6)
val LightSurfaceVariant = Color(0xFFE0E3E6)
val LightOnSurfaceVariant = Color(0xFF44474D)
val LightOutline = Color(0xFF74777D)
val LightOutlineVariant = Color(0xFFC4C7CD)
val LightInverseSurface = Color(0xFF2F3032)
val LightInverseOnSurface = Color(0xFFF1F2F4)
val LightInversePrimary = Color(0xFFB8C1F5)
val LightSurfaceTint = Color(0xFF5A67D8)
val LightScrim = Color(0xFF000000)

// Dark Theme Colors
val DarkPrimary = Color(0xFFB8C1F5)
val DarkOnPrimary = Color(0xFF262E5E)
val DarkPrimaryContainer = Color(0xFF3D4478)
val DarkOnPrimaryContainer = Color(0xFFDCE4FB)
val DarkSecondary = Color(0xFFA0B0E8)
val DarkOnSecondary = Color(0xFF2A3568)
val DarkSecondaryContainer = Color(0xFF465080)
val DarkOnSecondaryContainer = Color(0xFFD8E3FA)
val DarkTertiary = Color(0xFF9AA8E0)
val DarkOnTertiary = Color(0xFF222A58)
val DarkTertiaryContainer = Color(0xFF374070)
val DarkOnTertiaryContainer = Color(0xFFD2DCF8)
val DarkError = Color(0xFFEF9A9A)
val DarkOnError = Color(0xFF5C1313)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFFFEBEE)
val DarkBackground = Color(0xFF12141A)
val DarkOnBackground = Color(0xFFE3E5E7)
val DarkSurface = Color(0xFF1A1C22)
val DarkOnSurface = Color(0xFFE3E5E7)
val DarkSurfaceContainer = Color(0xFF1E2026)
val DarkSurfaceContainerHigh = Color(0xFF282A30)
val DarkSurfaceContainerHighest = Color(0xFF36383E)
val DarkSurfaceVariant = Color(0xFF36383E)
val DarkOnSurfaceVariant = Color(0xFFC4C7CD)
val DarkOutline = Color(0xFF8E9197)
val DarkOutlineVariant = Color(0xFF44474D)
val DarkInverseSurface = Color(0xFFE3E5E7)
val DarkInverseOnSurface = Color(0xFF2F3032)
val DarkInversePrimary = Color(0xFF5A67D8)
val DarkSurfaceTint = Color(0xFFB8C1F5)
val DarkScrim = Color(0xFF000000)

// Default Financial Colors - Light Theme
val LightIncome = Color(0xFF2E7D32)
val LightIncomeContainer = Color(0xFFC8E6C9)
val LightOnIncomeContainer = Color(0xFF1B5E20)
val LightExpense = Color(0xFFC62828)
val LightExpenseContainer = Color(0xFFFFCDD2)
val LightOnExpenseContainer = Color(0xFFB71C1C)
val LightBudgetWarning = Color(0xFFEF6C00)
val LightBudgetWarningContainer = Color(0xFFFFE0B2)
val LightBudgetDanger = Color(0xFFD32F2F)
val LightBudgetDangerContainer = Color(0xFFFFCDD2)

// Default Financial Colors - Dark Theme
val DarkIncome = Color(0xFF81C784)
val DarkIncomeContainer = Color(0xFF388E3C)
val DarkOnIncomeContainer = Color(0xFFC8E6C9)
val DarkExpense = Color(0xFFEF9A9A)
val DarkExpenseContainer = Color(0xFFC62828)
val DarkOnExpenseContainer = Color(0xFFFFCDD2)
val DarkBudgetWarning = Color(0xFFFFB74D)
val DarkBudgetWarningContainer = Color(0xFFE65100)
val DarkBudgetDanger = Color(0xFFEF5350)
val DarkBudgetDangerContainer = Color(0xFFC62828)

// ============================================================
// 薄荷奶绿 Theme (Mint Milk) — 马卡龙色系
// primary=#A8E6CF, secondary=#DCEDC1, tertiary=#FFD3B6
// ============================================================

// Light — 奶油背景 #FBF9F6
val MintMilkLightPrimary = Color(0xFFA8E6CF)
val MintMilkLightOnPrimary = Color(0xFF003D2E)
val MintMilkLightPrimaryContainer = Color(0xFFD4F5E8)
val MintMilkLightOnPrimaryContainer = Color(0xFF003D2E)
val MintMilkLightSecondary = Color(0xFFDCEDC1)
val MintMilkLightOnSecondary = Color(0xFF2D3A00)
val MintMilkLightSecondaryContainer = Color(0xFFF0F8E0)
val MintMilkLightOnSecondaryContainer = Color(0xFF1A2500)
val MintMilkLightTertiary = Color(0xFFFFD3B6)
val MintMilkLightOnTertiary = Color(0xFF3D2A10)
val MintMilkLightTertiaryContainer = Color(0xFFFFF0E0)
val MintMilkLightOnTertiaryContainer = Color(0xFF2D1A08)
val MintMilkLightError = Color(0xFFE57373)
val MintMilkLightOnError = Color(0xFFFFFFFF)
val MintMilkLightErrorContainer = Color(0xFFFFEBEE)
val MintMilkLightOnErrorContainer = Color(0xFF5C1313)
val MintMilkLightBackground = Color(0xFFFBF9F6)  // 奶油色
val MintMilkLightOnBackground = Color(0xFF2D2D2D)
val MintMilkLightSurface = Color(0xFFFFFFFF)  // 纯白
val MintMilkLightOnSurface = Color(0xFF2D2D2D)
val MintMilkLightSurfaceContainer = Color(0xFFF5F3F0)
val MintMilkLightSurfaceContainerHigh = Color(0xFFEFECE8)
val MintMilkLightSurfaceContainerHighest = Color(0xFFE8E5E0)
val MintMilkLightSurfaceVariant = Color(0xFFE8E5E0)
val MintMilkLightOnSurfaceVariant = Color(0xFF4A4A4A)
val MintMilkLightOutline = Color(0xFF7A7A7A)
val MintMilkLightOutlineVariant = Color(0xFFC8C8C8)
val MintMilkLightInverseSurface = Color(0xFF2D2D2D)
val MintMilkLightInverseOnSurface = Color(0xFFF5F3F0)
val MintMilkLightInversePrimary = Color(0xFFA8E6CF)
val MintMilkLightSurfaceTint = Color(0xFFA8E6CF)
val MintMilkLightScrim = Color(0xFF000000)

// Dark — 深灰蓝背景 #111318
val MintMilkDarkPrimary = Color(0xFF80D4B0)
val MintMilkDarkOnPrimary = Color(0xFF003D2E)
val MintMilkDarkPrimaryContainer = Color(0xFF005540)
val MintMilkDarkOnPrimaryContainer = Color(0xFFD4F5E8)
val MintMilkDarkSecondary = Color(0xFFB8D4A0)
val MintMilkDarkOnSecondary = Color(0xFF2D3A00)
val MintMilkDarkSecondaryContainer = Color(0xFF3D4A20)
val MintMilkDarkOnSecondaryContainer = Color(0xFFF0F8E0)
val MintMilkDarkTertiary = Color(0xFFE8C4A8)
val MintMilkDarkOnTertiary = Color(0xFF3D2A10)
val MintMilkDarkTertiaryContainer = Color(0xFF4D3A20)
val MintMilkDarkOnTertiaryContainer = Color(0xFFFFF0E0)
val MintMilkDarkError = Color(0xFFCF7A7A)
val MintMilkDarkOnError = Color(0xFF5C1313)
val MintMilkDarkErrorContainer = Color(0xFF8C2525)
val MintMilkDarkOnErrorContainer = Color(0xFFFFDAD6)
val MintMilkDarkBackground = Color(0xFF111318)  // 深灰蓝
val MintMilkDarkOnBackground = Color(0xFFE4E4E4)
val MintMilkDarkSurface = Color(0xFF1A1C22)  // 深灰
val MintMilkDarkOnSurface = Color(0xFFE4E4E4)
val MintMilkDarkSurfaceContainer = Color(0xFF1E2028)  // 半透明深灰
val MintMilkDarkSurfaceContainerHigh = Color(0xFF282A32)
val MintMilkDarkSurfaceContainerHighest = Color(0xFF36383E)
val MintMilkDarkSurfaceVariant = Color(0xFF36383E)
val MintMilkDarkOnSurfaceVariant = Color(0xFFC4C4C4)
val MintMilkDarkOutline = Color(0xFF8E8E8E)
val MintMilkDarkOutlineVariant = Color(0xFF4A4A4A)
val MintMilkDarkInverseSurface = Color(0xFFE4E4E4)
val MintMilkDarkInverseOnSurface = Color(0xFF2D2D2D)
val MintMilkDarkInversePrimary = Color(0xFFA8E6CF)
val MintMilkDarkSurfaceTint = Color(0xFF80D4B0)
val MintMilkDarkScrim = Color(0xFF000000)

// MintMilk Financial Colors — 柔和版本
val MintMilkLightIncome = Color(0xFF7BC8A4)
val MintMilkLightIncomeContainer = Color(0xFFD8F5E8)
val MintMilkLightOnIncomeContainer = Color(0xFF004D38)
val MintMilkLightExpense = Color(0xFFE57373)
val MintMilkLightExpenseContainer = Color(0xFFFFDAD6)
val MintMilkLightOnExpenseContainer = Color(0xFF5C2020)
val MintMilkLightBudgetWarning = Color(0xFFFFB74D)
val MintMilkLightBudgetWarningContainer = Color(0xFFFFF0C2)
val MintMilkLightBudgetDanger = Color(0xFFE56565)
val MintMilkLightBudgetDangerContainer = Color(0xFFFFCDD2)

val MintMilkDarkIncome = Color(0xFF80C8A8)
val MintMilkDarkIncomeContainer = Color(0xFF005540)
val MintMilkDarkOnIncomeContainer = Color(0xFFD8F5E8)
val MintMilkDarkExpense = Color(0xFFCF7A7A)
val MintMilkDarkExpenseContainer = Color(0xFF8C2525)
val MintMilkDarkOnExpenseContainer = Color(0xFFFFDAD6)
val MintMilkDarkBudgetWarning = Color(0xFFE8B860)
val MintMilkDarkBudgetWarningContainer = Color(0xFF5C4A20)
val MintMilkDarkBudgetDanger = Color(0xFFCF6565)
val MintMilkDarkBudgetDangerContainer = Color(0xFF8C2020)

// MintMilk Glow Colors — 弥散光斑
val MintMilkLightGlowPrimary = Color(0x1AA8E6CF)  // alpha 0.10
val MintMilkLightGlowSecondary = Color(0x18DCEDC1)  // alpha 0.09
val MintMilkLightGlowAccent = Color(0x1AFFD3B6)  // alpha 0.10
val MintMilkDarkGlowPrimary = Color(0x0D80D4B0)  // alpha 0.05 (深色更低)
val MintMilkDarkGlowSecondary = Color(0x0AB8D4A0)  // alpha 0.04
val MintMilkDarkGlowAccent = Color(0x0CE8C4A8)  // alpha 0.05

// ============================================================
// 薰衣草紫 Theme (Lavender) — 马卡龙色系
// primary=#DCD3FF, secondary=#C4FAF8, tertiary=#FFDFD3
// ============================================================

// Light
val LavenderLightPrimary = Color(0xFFDCD3FF)
val LavenderLightOnPrimary = Color(0xFF3D2A60)
val LavenderLightPrimaryContainer = Color(0xFFF0E8FF)
val LavenderLightOnPrimaryContainer = Color(0xFF2D1A4D)
val LavenderLightSecondary = Color(0xFFC4FAF8)
val LavenderLightOnSecondary = Color(0xFF003544)
val LavenderLightSecondaryContainer = Color(0xFFE0F8F8)
val LavenderLightOnSecondaryContainer = Color(0xFF001E28)
val LavenderLightTertiary = Color(0xFFFFDFD3)
val LavenderLightOnTertiary = Color(0xFF3D2A20)
val LavenderLightTertiaryContainer = Color(0xFFFFF0E8)
val LavenderLightOnTertiaryContainer = Color(0xFF2D1A15)
val LavenderLightError = Color(0xFFE57373)
val LavenderLightOnError = Color(0xFFFFFFFF)
val LavenderLightErrorContainer = Color(0xFFFFEBEE)
val LavenderLightOnErrorContainer = Color(0xFF5C1313)
val LavenderLightBackground = Color(0xFFFBF9F6)
val LavenderLightOnBackground = Color(0xFF2D2D2D)
val LavenderLightSurface = Color(0xFFFFFFFF)
val LavenderLightOnSurface = Color(0xFF2D2D2D)
val LavenderLightSurfaceContainer = Color(0xFFF5F3F0)
val LavenderLightSurfaceContainerHigh = Color(0xFFEFECE8)
val LavenderLightSurfaceContainerHighest = Color(0xFFE8E5E0)
val LavenderLightSurfaceVariant = Color(0xFFE8E5E0)
val LavenderLightOnSurfaceVariant = Color(0xFF4A4A4A)
val LavenderLightOutline = Color(0xFF7A7A7A)
val LavenderLightOutlineVariant = Color(0xFFC8C8C8)
val LavenderLightInverseSurface = Color(0xFF2D2D2D)
val LavenderLightInverseOnSurface = Color(0xFFF5F3F0)
val LavenderLightInversePrimary = Color(0xFFDCD3FF)
val LavenderLightSurfaceTint = Color(0xFFDCD3FF)
val LavenderLightScrim = Color(0xFF000000)

// Dark
val LavenderDarkPrimary = Color(0xFFB8A8E8)
val LavenderDarkOnPrimary = Color(0xFF3D2A60)
val LavenderDarkPrimaryContainer = Color(0xFF5D4A80)
val LavenderDarkOnPrimaryContainer = Color(0xFFF0E8FF)
val LavenderDarkSecondary = Color(0xFF80D8D4)
val LavenderDarkOnSecondary = Color(0xFF003544)
val LavenderDarkSecondaryContainer = Color(0xFF004D5A)
val LavenderDarkOnSecondaryContainer = Color(0xFFE0F8F8)
val LavenderDarkTertiary = Color(0xFFE8C4B8)
val LavenderDarkOnTertiary = Color(0xFF3D2A20)
val LavenderDarkTertiaryContainer = Color(0xFF5D4A40)
val LavenderDarkOnTertiaryContainer = Color(0xFFFFF0E8)
val LavenderDarkError = Color(0xFFCF7A7A)
val LavenderDarkOnError = Color(0xFF5C1313)
val LavenderDarkErrorContainer = Color(0xFF8C2525)
val LavenderDarkOnErrorContainer = Color(0xFFFFDAD6)
val LavenderDarkBackground = Color(0xFF111318)
val LavenderDarkOnBackground = Color(0xFFE4E4E4)
val LavenderDarkSurface = Color(0xFF1A1C22)
val LavenderDarkOnSurface = Color(0xFFE4E4E4)
val LavenderDarkSurfaceContainer = Color(0xFF1E2028)
val LavenderDarkSurfaceContainerHigh = Color(0xFF282A32)
val LavenderDarkSurfaceContainerHighest = Color(0xFF36383E)
val LavenderDarkSurfaceVariant = Color(0xFF36383E)
val LavenderDarkOnSurfaceVariant = Color(0xFFC4C4C4)
val LavenderDarkOutline = Color(0xFF8E8E8E)
val LavenderDarkOutlineVariant = Color(0xFF4A4A4A)
val LavenderDarkInverseSurface = Color(0xFFE4E4E4)
val LavenderDarkInverseOnSurface = Color(0xFF2D2D2D)
val LavenderDarkInversePrimary = Color(0xFFDCD3FF)
val LavenderDarkSurfaceTint = Color(0xFFB8A8E8)
val LavenderDarkScrim = Color(0xFF000000)

// Lavender Financial Colors
val LavenderLightIncome = Color(0xFF81C784)
val LavenderLightIncomeContainer = Color(0xFFC8E6C9)
val LavenderLightOnIncomeContainer = Color(0xFF1B5E20)
val LavenderLightExpense = Color(0xFFCE93D8)
val LavenderLightExpenseContainer = Color(0xFFF3E5F5)
val LavenderLightOnExpenseContainer = Color(0xFF4A148C)
val LavenderLightBudgetWarning = Color(0xFFFFE082)
val LavenderLightBudgetWarningContainer = Color(0xFFFFF8E0)
val LavenderLightBudgetDanger = Color(0xFFE56565)
val LavenderLightBudgetDangerContainer = Color(0xFFFFCDD2)

val LavenderDarkIncome = Color(0xFF80C880)
val LavenderDarkIncomeContainer = Color(0xFF388E3C)
val LavenderDarkOnIncomeContainer = Color(0xFFC8E6C9)
val LavenderDarkExpense = Color(0xFFB8A0C8)
val LavenderDarkExpenseContainer = Color(0xFF6A4A80)
val LavenderDarkOnExpenseContainer = Color(0xFFF3E5F5)
val LavenderDarkBudgetWarning = Color(0xFFE8C860)
val LavenderDarkBudgetWarningContainer = Color(0xFF5C4A20)
val LavenderDarkBudgetDanger = Color(0xFFCF6565)
val LavenderDarkBudgetDangerContainer = Color(0xFF8C2020)

// Lavender Glow Colors
val LavenderLightGlowPrimary = Color(0x1ADCD3FF)
val LavenderLightGlowSecondary = Color(0x15C4FAF8)
val LavenderLightGlowAccent = Color(0x1AFFDFD3)
val LavenderDarkGlowPrimary = Color(0x0DB8A8E8)
val LavenderDarkGlowSecondary = Color(0x0880D8D4)
val LavenderDarkGlowAccent = Color(0x0CE8C4B8)

// ============================================================
// 暖阳蜜桃 Theme (Warm Peach) — 马卡龙色系
// primary=#FFDFD3, secondary=#FFE0B2, tertiary=#B5EAD7
// ============================================================

// Light
val WarmPeachLightPrimary = Color(0xFFFFDFD3)
val WarmPeachLightOnPrimary = Color(0xFF3D2A20)
val WarmPeachLightPrimaryContainer = Color(0xFFFFF0E8)
val WarmPeachLightOnPrimaryContainer = Color(0xFF2D1A15)
val WarmPeachLightSecondary = Color(0xFFFFE0B2)
val WarmPeachLightOnSecondary = Color(0xFF3D2A00)
val WarmPeachLightSecondaryContainer = Color(0xFFFFF8E8)
val WarmPeachLightOnSecondaryContainer = Color(0xFF2D1A00)
val WarmPeachLightTertiary = Color(0xFFB5EAD7)
val WarmPeachLightOnTertiary = Color(0xFF003828)
val WarmPeachLightTertiaryContainer = Color(0xFFE0F5E8)
val WarmPeachLightOnTertiaryContainer = Color(0xFF002818)
val WarmPeachLightError = Color(0xFFE57373)
val WarmPeachLightOnError = Color(0xFFFFFFFF)
val WarmPeachLightErrorContainer = Color(0xFFFFEBEE)
val WarmPeachLightOnErrorContainer = Color(0xFF5C1313)
val WarmPeachLightBackground = Color(0xFFFBF9F6)
val WarmPeachLightOnBackground = Color(0xFF2D2D2D)
val WarmPeachLightSurface = Color(0xFFFFFFFF)
val WarmPeachLightOnSurface = Color(0xFF2D2D2D)
val WarmPeachLightSurfaceContainer = Color(0xFFF5F3F0)
val WarmPeachLightSurfaceContainerHigh = Color(0xFFEFECE8)
val WarmPeachLightSurfaceContainerHighest = Color(0xFFE8E5E0)
val WarmPeachLightSurfaceVariant = Color(0xFFE8E5E0)
val WarmPeachLightOnSurfaceVariant = Color(0xFF4A4A4A)
val WarmPeachLightOutline = Color(0xFF7A7A7A)
val WarmPeachLightOutlineVariant = Color(0xFFC8C8C8)
val WarmPeachLightInverseSurface = Color(0xFF2D2D2D)
val WarmPeachLightInverseOnSurface = Color(0xFFF5F3F0)
val WarmPeachLightInversePrimary = Color(0xFFFFDFD3)
val WarmPeachLightSurfaceTint = Color(0xFFFFDFD3)
val WarmPeachLightScrim = Color(0xFF000000)

// Dark
val WarmPeachDarkPrimary = Color(0xFFE8C4B8)
val WarmPeachDarkOnPrimary = Color(0xFF3D2A20)
val WarmPeachDarkPrimaryContainer = Color(0xFF5D4A40)
val WarmPeachDarkOnPrimaryContainer = Color(0xFFFFF0E8)
val WarmPeachDarkSecondary = Color(0xFFE8C890)
val WarmPeachDarkOnSecondary = Color(0xFF3D2A00)
val WarmPeachDarkSecondaryContainer = Color(0xFF5D4A20)
val WarmPeachDarkOnSecondaryContainer = Color(0xFFFFF8E8)
val WarmPeachDarkTertiary = Color(0xFF80C8A8)
val WarmPeachDarkOnTertiary = Color(0xFF003828)
val WarmPeachDarkTertiaryContainer = Color(0xFF004D38)
val WarmPeachDarkOnTertiaryContainer = Color(0xFFE0F5E8)
val WarmPeachDarkError = Color(0xFFCF7A7A)
val WarmPeachDarkOnError = Color(0xFF5C1313)
val WarmPeachDarkErrorContainer = Color(0xFF8C2525)
val WarmPeachDarkOnErrorContainer = Color(0xFFFFDAD6)
val WarmPeachDarkBackground = Color(0xFF111318)
val WarmPeachDarkOnBackground = Color(0xFFE4E4E4)
val WarmPeachDarkSurface = Color(0xFF1A1C22)
val WarmPeachDarkOnSurface = Color(0xFFE4E4E4)
val WarmPeachDarkSurfaceContainer = Color(0xFF1E2028)
val WarmPeachDarkSurfaceContainerHigh = Color(0xFF282A32)
val WarmPeachDarkSurfaceContainerHighest = Color(0xFF36383E)
val WarmPeachDarkSurfaceVariant = Color(0xFF36383E)
val WarmPeachDarkOnSurfaceVariant = Color(0xFFC4C4C4)
val WarmPeachDarkOutline = Color(0xFF8E8E8E)
val WarmPeachDarkOutlineVariant = Color(0xFF4A4A4A)
val WarmPeachDarkInverseSurface = Color(0xFFE4E4E4)
val WarmPeachDarkInverseOnSurface = Color(0xFF2D2D2D)
val WarmPeachDarkInversePrimary = Color(0xFFFFDFD3)
val WarmPeachDarkSurfaceTint = Color(0xFFE8C4B8)
val WarmPeachDarkScrim = Color(0xFF000000)

// WarmPeach Financial Colors
val WarmPeachLightIncome = Color(0xFFB5EAD7)
val WarmPeachLightIncomeContainer = Color(0xFFE0F5E8)
val WarmPeachLightOnIncomeContainer = Color(0xFF004D38)
val WarmPeachLightExpense = Color(0xFFFF8A65)
val WarmPeachLightExpenseContainer = Color(0xFFFFE0D8)
val WarmPeachLightOnExpenseContainer = Color(0xFF5C3020)
val WarmPeachLightBudgetWarning = Color(0xFFFFE0B2)
val WarmPeachLightBudgetWarningContainer = Color(0xFFFFF8E8)
val WarmPeachLightBudgetDanger = Color(0xFFE56565)
val WarmPeachLightBudgetDangerContainer = Color(0xFFFFCDD2)

val WarmPeachDarkIncome = Color(0xFF80C8A8)
val WarmPeachDarkIncomeContainer = Color(0xFF004D38)
val WarmPeachDarkOnIncomeContainer = Color(0xFFE0F5E8)
val WarmPeachDarkExpense = Color(0xFFCF8A65)
val WarmPeachDarkExpenseContainer = Color(0xFF8C4020)
val WarmPeachDarkOnExpenseContainer = Color(0xFFFFE0D8)
val WarmPeachDarkBudgetWarning = Color(0xFFE8C890)
val WarmPeachDarkBudgetWarningContainer = Color(0xFF5D4A20)
val WarmPeachDarkBudgetDanger = Color(0xFFCF6565)
val WarmPeachDarkBudgetDangerContainer = Color(0xFF8C2020)

// WarmPeach Glow Colors
val WarmPeachLightGlowPrimary = Color(0x1AFFDFD3)
val WarmPeachLightGlowSecondary = Color(0x18FFE0B2)
val WarmPeachLightGlowAccent = Color(0x15B5EAD7)
val WarmPeachDarkGlowPrimary = Color(0x0DE8C4B8)
val WarmPeachDarkGlowSecondary = Color(0x0AE8C890)
val WarmPeachDarkGlowAccent = Color(0x0880C8A8)