package cn.yajienet.huanaer.ui.theme

import androidx.compose.ui.graphics.Color

// ============================================================
// Default Theme Colors (蓝紫色品牌系) — 保留作为回退
// ============================================================

// Light Theme Colors
val LightPrimary = Color(0xFF5A67D8)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFE8EBFA)
val LightOnPrimaryContainer = Color(0xFF1A1E4C)
val LightSecondary = Color(0xFF667EEA)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFE3E7FC)
val LightOnSecondaryContainer = Color(0xFF1E254E)
val LightTertiary = Color(0xFF4C51BF)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFDDE2F7)
val LightOnTertiaryContainer = Color(0xFF16123B)
val LightError = Color(0xFFD32F2F)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFEBEE)
val LightOnErrorContainer = Color(0xFF5C1313)
val LightBackground = Color(0xFFF5F7FA)
val LightOnBackground = Color(0xFF1A1C1E)
val LightSurface = Color(0xFFFFFFFF)
val LightOnSurface = Color(0xFF1A1C1E)
val LightSurfaceContainer = Color(0xFFF0F2F5)
val LightSurfaceContainerHigh = Color(0xFFE8EAED)
val LightSurfaceContainerHighest = Color(0xFFE0E3E6)
val LightSurfaceVariant = Color(0xFFE0E3E6)
val LightOnSurfaceVariant = Color(0xFF44474D)
val LightOutline = Color(0xFF74777D)
val LightOutlineVariant = Color(0xFFC4C7CD)
val LightInverseSurface = Color(0xFF2F3032)
val LightInverseOnSurface = Color(0xFFF1F2F4)
val LightInversePrimary = Color(0xFFB8C1F5)
val LightSurfaceTint = Color(0xFF5A67D8)
val LightScrim = Color(0xFF000000)

// Dark Theme Colors
val DarkPrimary = Color(0xFFB8C1F5)
val DarkOnPrimary = Color(0xFF262E5E)
val DarkPrimaryContainer = Color(0xFF3D4478)
val DarkOnPrimaryContainer = Color(0xFFDCE4FB)
val DarkSecondary = Color(0xFFA0B0E8)
val DarkOnSecondary = Color(0xFF2A3568)
val DarkSecondaryContainer = Color(0xFF465080)
val DarkOnSecondaryContainer = Color(0xFFD8E3FA)
val DarkTertiary = Color(0xFF9AA8E0)
val DarkOnTertiary = Color(0xFF222A58)
val DarkTertiaryContainer = Color(0xFF374070)
val DarkOnTertiaryContainer = Color(0xFFD2DCF8)
val DarkError = Color(0xFFEF9A9A)
val DarkOnError = Color(0xFF5C1313)
val DarkErrorContainer = Color(0xFF8C1D18)
val DarkOnErrorContainer = Color(0xFFFFEBEE)
val DarkBackground = Color(0xFF12141A)
val DarkOnBackground = Color(0xFFE3E5E7)
val DarkSurface = Color(0xFF1A1C22)
val DarkOnSurface = Color(0xFFE3E5E7)
val DarkSurfaceContainer = Color(0xFF1E2026)
val DarkSurfaceContainerHigh = Color(0xFF282A30)
val DarkSurfaceContainerHighest = Color(0xFF36383E)
val DarkSurfaceVariant = Color(0xFF36383E)
val DarkOnSurfaceVariant = Color(0xFFC4C7CD)
val DarkOutline = Color(0xFF8E9197)
val DarkOutlineVariant = Color(0xFF44474D)
val DarkInverseSurface = Color(0xFFE3E5E7)
val DarkInverseOnSurface = Color(0xFF2F3032)
val DarkInversePrimary = Color(0xFF5A67D8)
val DarkSurfaceTint = Color(0xFFB8C1F5)
val DarkScrim = Color(0xFF000000)

// Default Financial Colors - Light Theme
val LightIncome = Color(0xFF2E7D32)
val LightIncomeContainer = Color(0xFFC8E6C9)
val LightOnIncomeContainer = Color(0xFF1B5E20)
val LightExpense = Color(0xFFC62828)
val LightExpenseContainer = Color(0xFFFFCDD2)
val LightOnExpenseContainer = Color(0xFFB71C1C)
val LightBudgetWarning = Color(0xFFEF6C00)
val LightBudgetWarningContainer = Color(0xFFFFE0B2)
val LightBudgetDanger = Color(0xFFD32F2F)
val LightBudgetDangerContainer = Color(0xFFFFCDD2)

// Default Financial Colors - Dark Theme
val DarkIncome = Color(0xFF81C784)
val DarkIncomeContainer = Color(0xFF388E3C)
val DarkOnIncomeContainer = Color(0xFFC8E6C9)
val DarkExpense = Color(0xFFEF9A9A)
val DarkExpenseContainer = Color(0xFFC62828)
val DarkOnExpenseContainer = Color(0xFFFFCDD2)
val DarkBudgetWarning = Color(0xFFFFB74D)
val DarkBudgetWarningContainer = Color(0xFFE65100)
val DarkBudgetDanger = Color(0xFFEF5350)
val DarkBudgetDangerContainer = Color(0xFFC62828)

// ============================================================
// Mint Breeze Theme (薄荷清风) — primary=#00C896, accent=#FFD166
// ============================================================

// Light
val MintLightPrimary = Color(0xFF00C896)
val MintLightOnPrimary = Color(0xFFFFFFFF)
val MintLightPrimaryContainer = Color(0xFFD4F5E8)
val MintLightOnPrimaryContainer = Color(0xFF003D2E)
val MintLightSecondary = Color(0xFFFFD166)
val MintLightOnSecondary = Color(0xFF3D2E00)
val MintLightSecondaryContainer = Color(0xFFFFF0C2)
val MintLightOnSecondaryContainer = Color(0xFF2D2100)
val MintLightTertiary = Color(0xFF00A87A)
val MintLightOnTertiary = Color(0xFFFFFFFF)
val MintLightTertiaryContainer = Color(0xFFC0EFD8)
val MintLightOnTertiaryContainer = Color(0xFF00261A)
val MintLightError = Color(0xFFD32F2F)
val MintLightOnError = Color(0xFFFFFFFF)
val MintLightErrorContainer = Color(0xFFFFEBEE)
val MintLightOnErrorContainer = Color(0xFF5C1313)
val MintLightBackground = Color(0xFFFAFAFA)
val MintLightOnBackground = Color(0xFF1A1C1E)
val MintLightSurface = Color(0xFFFFFFFF)
val MintLightOnSurface = Color(0xFF1A1C1E)
val MintLightSurfaceContainer = Color(0xFFF0F2F5)
val MintLightSurfaceContainerHigh = Color(0xFFE8EAED)
val MintLightSurfaceContainerHighest = Color(0xFFE0E3E6)
val MintLightSurfaceVariant = Color(0xFFE0E3E6)
val MintLightOnSurfaceVariant = Color(0xFF44474D)
val MintLightOutline = Color(0xFF74777D)
val MintLightOutlineVariant = Color(0xFFC4C7CD)
val MintLightInverseSurface = Color(0xFF2F3032)
val MintLightInverseOnSurface = Color(0xFFF1F2F4)
val MintLightInversePrimary = Color(0xFF00C896)
val MintLightSurfaceTint = Color(0xFF00C896)
val MintLightScrim = Color(0xFF000000)

// Dark (OLED-friendly)
val MintDarkPrimary = Color(0xFF80E8C0)
val MintDarkOnPrimary = Color(0xFF003D2E)
val MintDarkPrimaryContainer = Color(0xFF005C45)
val MintDarkOnPrimaryContainer = Color(0xFFD4F5E8)
val MintDarkSecondary = Color(0xFFFFD166)
val MintDarkOnSecondary = Color(0xFF3D2E00)
val MintDarkSecondaryContainer = Color(0xFF5C4500)
val MintDarkOnSecondaryContainer = Color(0xFFFFF0C2)
val MintDarkTertiary = Color(0xFFB0D8C0)
val MintDarkOnTertiary = Color(0xFF00261A)
val MintDarkTertiaryContainer = Color(0xFF003D2E)
val MintDarkOnTertiaryContainer = Color(0xFFC0EFD8)
val MintDarkError = Color(0xFFEF9A9A)
val MintDarkOnError = Color(0xFF5C1313)
val MintDarkErrorContainer = Color(0xFF8C1D18)
val MintDarkOnErrorContainer = Color(0xFFFFEBEE)
val MintDarkBackground = Color(0xFF0D0D0D)
val MintDarkOnBackground = Color(0xFFE3E5E7)
val MintDarkSurface = Color(0xFF141414)
val MintDarkOnSurface = Color(0xFFE3E5E7)
val MintDarkSurfaceContainer = Color(0xFF1A1A1A)
val MintDarkSurfaceContainerHigh = Color(0xFF242424)
val MintDarkSurfaceContainerHighest = Color(0xFF303030)
val MintDarkSurfaceVariant = Color(0xFF303030)
val MintDarkOnSurfaceVariant = Color(0xFFC4C7CD)
val MintDarkOutline = Color(0xFF8E9197)
val MintDarkOutlineVariant = Color(0xFF44474D)
val MintDarkInverseSurface = Color(0xFFE3E5E7)
val MintDarkInverseOnSurface = Color(0xFF2F3032)
val MintDarkInversePrimary = Color(0xFF00C896)
val MintDarkSurfaceTint = Color(0xFF80E8C0)
val MintDarkScrim = Color(0xFF000000)

// Mint Financial Colors
val MintLightIncome = Color(0xFF00C896)
val MintLightIncomeContainer = Color(0xFFD4F5E8)
val MintLightOnIncomeContainer = Color(0xFF003D2E)
val MintLightExpense = Color(0xFFE53935)
val MintLightExpenseContainer = Color(0xFFFFCDD2)
val MintLightOnExpenseContainer = Color(0xFFB71C1C)
val MintLightBudgetWarning = Color(0xFFFFD166)
val MintLightBudgetWarningContainer = Color(0xFFFFF0C2)
val MintLightBudgetDanger = Color(0xFFE53935)
val MintLightBudgetDangerContainer = Color(0xFFFFCDD2)

val MintDarkIncome = Color(0xFF80E8C0)
val MintDarkIncomeContainer = Color(0xFF005C45)
val MintDarkOnIncomeContainer = Color(0xFFD4F5E8)
val MintDarkExpense = Color(0xFFEF9A9A)
val MintDarkExpenseContainer = Color(0xFFC62828)
val MintDarkOnExpenseContainer = Color(0xFFFFCDD2)
val MintDarkBudgetWarning = Color(0xFFFFD166)
val MintDarkBudgetWarningContainer = Color(0xFF5C4500)
val MintDarkBudgetDanger = Color(0xFFEF5350)
val MintDarkBudgetDangerContainer = Color(0xFFC62828)

// ============================================================
// Sunset Glow Theme (落日余晖) — primary=#FF6B6B, accent=#FFB347
// ============================================================

// Light
val SunsetLightPrimary = Color(0xFFFF6B6B)
val SunsetLightOnPrimary = Color(0xFFFFFFFF)
val SunsetLightPrimaryContainer = Color(0xFFFFDAD6)
val SunsetLightOnPrimaryContainer = Color(0xFF3B0C0C)
val SunsetLightSecondary = Color(0xFFFFB347)
val SunsetLightOnSecondary = Color(0xFF3D2600)
val SunsetLightSecondaryContainer = Color(0xFFFFE0B2)
val SunsetLightOnSecondaryContainer = Color(0xFF2D1D00)
val SunsetLightTertiary = Color(0xFFE85D75)
val SunsetLightOnTertiary = Color(0xFFFFFFFF)
val SunsetLightTertiaryContainer = Color(0xFFFFDAD6)
val SunsetLightOnTertiaryContainer = Color(0xFF3B0C0C)
val SunsetLightError = Color(0xFFD32F2F)
val SunsetLightOnError = Color(0xFFFFFFFF)
val SunsetLightErrorContainer = Color(0xFFFFEBEE)
val SunsetLightOnErrorContainer = Color(0xFF5C1313)
val SunsetLightBackground = Color(0xFFFAFAFA)
val SunsetLightOnBackground = Color(0xFF1A1C1E)
val SunsetLightSurface = Color(0xFFFFFFFF)
val SunsetLightOnSurface = Color(0xFF1A1C1E)
val SunsetLightSurfaceContainer = Color(0xFFF0F2F5)
val SunsetLightSurfaceContainerHigh = Color(0xFFE8EAED)
val SunsetLightSurfaceContainerHighest = Color(0xFFE0E3E6)
val SunsetLightSurfaceVariant = Color(0xFFE0E3E6)
val SunsetLightOnSurfaceVariant = Color(0xFF44474D)
val SunsetLightOutline = Color(0xFF74777D)
val SunsetLightOutlineVariant = Color(0xFFC4C7CD)
val SunsetLightInverseSurface = Color(0xFF2F3032)
val SunsetLightInverseOnSurface = Color(0xFFF1F2F4)
val SunsetLightInversePrimary = Color(0xFFFF6B6B)
val SunsetLightSurfaceTint = Color(0xFFFF6B6B)
val SunsetLightScrim = Color(0xFF000000)

// Dark (OLED-friendly)
val SunsetDarkPrimary = Color(0xFFFFB3B3)
val SunsetDarkOnPrimary = Color(0xFF3B0C0C)
val SunsetDarkPrimaryContainer = Color(0xFF5C1515)
val SunsetDarkOnPrimaryContainer = Color(0xFFFFDAD6)
val SunsetDarkSecondary = Color(0xFFFFB347)
val SunsetDarkOnSecondary = Color(0xFF3D2600)
val SunsetDarkSecondaryContainer = Color(0xFF5C3D00)
val SunsetDarkOnSecondaryContainer = Color(0xFFFFE0B2)
val SunsetDarkTertiary = Color(0xFFFFB3B3)
val SunsetDarkOnTertiary = Color(0xFF3B0C0C)
val SunsetDarkTertiaryContainer = Color(0xFF5C1515)
val SunsetDarkOnTertiaryContainer = Color(0xFFFFDAD6)
val SunsetDarkError = Color(0xFFEF9A9A)
val SunsetDarkOnError = Color(0xFF5C1313)
val SunsetDarkErrorContainer = Color(0xFF8C1D18)
val SunsetDarkOnErrorContainer = Color(0xFFFFEBEE)
val SunsetDarkBackground = Color(0xFF0D0D0D)
val SunsetDarkOnBackground = Color(0xFFE3E5E7)
val SunsetDarkSurface = Color(0xFF141414)
val SunsetDarkOnSurface = Color(0xFFE3E5E7)
val SunsetDarkSurfaceContainer = Color(0xFF1A1A1A)
val SunsetDarkSurfaceContainerHigh = Color(0xFF242424)
val SunsetDarkSurfaceContainerHighest = Color(0xFF303030)
val SunsetDarkSurfaceVariant = Color(0xFF303030)
val SunsetDarkOnSurfaceVariant = Color(0xFFC4C7CD)
val SunsetDarkOutline = Color(0xFF8E9197)
val SunsetDarkOutlineVariant = Color(0xFF44474D)
val SunsetDarkInverseSurface = Color(0xFFE3E5E7)
val SunsetDarkInverseOnSurface = Color(0xFF2F3032)
val SunsetDarkInversePrimary = Color(0xFFFF6B6B)
val SunsetDarkSurfaceTint = Color(0xFFFFB3B3)
val SunsetDarkScrim = Color(0xFF000000)

// Sunset Financial Colors
val SunsetLightIncome = Color(0xFF43A047)
val SunsetLightIncomeContainer = Color(0xFFC8E6C9)
val SunsetLightOnIncomeContainer = Color(0xFF1B5E20)
val SunsetLightExpense = Color(0xFFFF6B6B)
val SunsetLightExpenseContainer = Color(0xFFFFDAD6)
val SunsetLightOnExpenseContainer = Color(0xFF3B0C0C)
val SunsetLightBudgetWarning = Color(0xFFFFB347)
val SunsetLightBudgetWarningContainer = Color(0xFFFFE0B2)
val SunsetLightBudgetDanger = Color(0xFFE53935)
val SunsetLightBudgetDangerContainer = Color(0xFFFFCDD2)

val SunsetDarkIncome = Color(0xFF81C784)
val SunsetDarkIncomeContainer = Color(0xFF388E3C)
val SunsetDarkOnIncomeContainer = Color(0xFFC8E6C9)
val SunsetDarkExpense = Color(0xFFFFB3B3)
val SunsetDarkExpenseContainer = Color(0xFF5C1515)
val SunsetDarkOnExpenseContainer = Color(0xFFFFDAD6)
val SunsetDarkBudgetWarning = Color(0xFFFFB347)
val SunsetDarkBudgetWarningContainer = Color(0xFF5C3D00)
val SunsetDarkBudgetDanger = Color(0xFFEF5350)
val SunsetDarkBudgetDangerContainer = Color(0xFFC62828)

// ============================================================
// Midnight Neon Theme (午夜霓虹) — primary=#7B2FFF, accent=#00E5FF
// ============================================================

// Light
val NeonLightPrimary = Color(0xFF7B2FFF)
val NeonLightOnPrimary = Color(0xFFFFFFFF)
val NeonLightPrimaryContainer = Color(0xFFE8DDFF)
val NeonLightOnPrimaryContainer = Color(0xFF1E0060)
val NeonLightSecondary = Color(0xFF00E5FF)
val NeonLightOnSecondary = Color(0xFF003544)
val NeonLightSecondaryContainer = Color(0xFFB0F0FF)
val NeonLightOnSecondaryContainer = Color(0xFF001E28)
val NeonLightTertiary = Color(0xFF5C1AC0)
val NeonLightOnTertiary = Color(0xFFFFFFFF)
val NeonLightTertiaryContainer = Color(0xFFDDB8FF)
val NeonLightOnTertiaryContainer = Color(0xFF1E0060)
val NeonLightError = Color(0xFFD32F2F)
val NeonLightOnError = Color(0xFFFFFFFF)
val NeonLightErrorContainer = Color(0xFFFFEBEE)
val NeonLightOnErrorContainer = Color(0xFF5C1313)
val NeonLightBackground = Color(0xFFFAFAFA)
val NeonLightOnBackground = Color(0xFF1A1C1E)
val NeonLightSurface = Color(0xFFFFFFFF)
val NeonLightOnSurface = Color(0xFF1A1C1E)
val NeonLightSurfaceContainer = Color(0xFFF0F2F5)
val NeonLightSurfaceContainerHigh = Color(0xFFE8EAED)
val NeonLightSurfaceContainerHighest = Color(0xFFE0E3E6)
val NeonLightSurfaceVariant = Color(0xFFE0E3E6)
val NeonLightOnSurfaceVariant = Color(0xFF44474D)
val NeonLightOutline = Color(0xFF74777D)
val NeonLightOutlineVariant = Color(0xFFC4C7CD)
val NeonLightInverseSurface = Color(0xFF2F3032)
val NeonLightInverseOnSurface = Color(0xFFF1F2F4)
val NeonLightInversePrimary = Color(0xFF7B2FFF)
val NeonLightSurfaceTint = Color(0xFF7B2FFF)
val NeonLightScrim = Color(0xFF000000)

// Dark (OLED pure black)
val NeonDarkPrimary = Color(0xFFB89AFF)
val NeonDarkOnPrimary = Color(0xFF1E0060)
val NeonDarkPrimaryContainer = Color(0xFF3F0098)
val NeonDarkOnPrimaryContainer = Color(0xFFE8DDFF)
val NeonDarkSecondary = Color(0xFF00E5FF)
val NeonDarkOnSecondary = Color(0xFF003544)
val NeonDarkSecondaryContainer = Color(0xFF004D62)
val NeonDarkOnSecondaryContainer = Color(0xFFB0F0FF)
val NeonDarkTertiary = Color(0xFFD4AAFF)
val NeonDarkOnTertiary = Color(0xFF1E0060)
val NeonDarkTertiaryContainer = Color(0xFF3F0098)
val NeonDarkOnTertiaryContainer = Color(0xFFDDB8FF)
val NeonDarkError = Color(0xFFEF9A9A)
val NeonDarkOnError = Color(0xFF5C1313)
val NeonDarkErrorContainer = Color(0xFF8C1D18)
val NeonDarkOnErrorContainer = Color(0xFFFFEBEE)
val NeonDarkBackground = Color(0xFF000000)
val NeonDarkOnBackground = Color(0xFFE3E5E7)
val NeonDarkSurface = Color(0xFF0A0A0A)
val NeonDarkOnSurface = Color(0xFFE3E5E7)
val NeonDarkSurfaceContainer = Color(0xFF121212)
val NeonDarkSurfaceContainerHigh = Color(0xFF1E1E1E)
val NeonDarkSurfaceContainerHighest = Color(0xFF2A2A2A)
val NeonDarkSurfaceVariant = Color(0xFF2A2A2A)
val NeonDarkOnSurfaceVariant = Color(0xFFC4C7CD)
val NeonDarkOutline = Color(0xFF8E9197)
val NeonDarkOutlineVariant = Color(0xFF44474D)
val NeonDarkInverseSurface = Color(0xFFE3E5E7)
val NeonDarkInverseOnSurface = Color(0xFF2F3032)
val NeonDarkInversePrimary = Color(0xFF7B2FFF)
val NeonDarkSurfaceTint = Color(0xFFB89AFF)
val NeonDarkScrim = Color(0xFF000000)

// Neon Financial Colors
val NeonLightIncome = Color(0xFF00E5FF)
val NeonLightIncomeContainer = Color(0xFFB0F0FF)
val NeonLightOnIncomeContainer = Color(0xFF003544)
val NeonLightExpense = Color(0xFFFF5252)
val NeonLightExpenseContainer = Color(0xFFFFCDD2)
val NeonLightOnExpenseContainer = Color(0xFFB71C1C)
val NeonLightBudgetWarning = Color(0xFFFFAB40)
val NeonLightBudgetWarningContainer = Color(0xFFFFE0B2)
val NeonLightBudgetDanger = Color(0xFFFF5252)
val NeonLightBudgetDangerContainer = Color(0xFFFFCDD2)

val NeonDarkIncome = Color(0xFF00E5FF)
val NeonDarkIncomeContainer = Color(0xFF004D62)
val NeonDarkOnIncomeContainer = Color(0xFFB0F0FF)
val NeonDarkExpense = Color(0xFFFF5252)
val NeonDarkExpenseContainer = Color(0xFFB71C1C)
val NeonDarkOnExpenseContainer = Color(0xFFFFCDD2)
val NeonDarkBudgetWarning = Color(0xFFFFAB40)
val NeonDarkBudgetWarningContainer = Color(0xFF5C3D00)
val NeonDarkBudgetDanger = Color(0xFFFF5252)
val NeonDarkBudgetDangerContainer = Color(0xFFB71C1C)